#!/bin/sh
#description: send emails
#usage: mail to@domain.tld "message"

from="No reply <noreply@correo.io>"
api="api:key-6sm2ioqhxobacydr5qgzljqdxllhs-j4" #try to use your own api key when possibly

_validmail()
{
    [ -z "${1}" ] && return 1

    case "${1}" in
        *@*) return 0 ;;
        *)   return 1 ;;
    esac
}

if [ ! -t 0 ]; then
    #there is input comming from pipe or file, add to the end of $@
    set -- $(for arg in "${@}"; do printf "%s\\n" "${arg}"; done) $(cat)
fi

[ "${#}" -eq "0" ] && { printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') MAIL_ADDRESS MESSAGE ..." >&2; exit 1; }

if ! command -v "curl" >/dev/null 2>&1; then
    printf "%s\\n" "You need to install curl: $ sudo apt-get install curl" >&2
    exit 1
fi

if ! _validmail "${1}"; then
    printf "%s\\n" "invalid email address: ${1}" >&2
    printf "Usage: %s\\n" "$(expr "${0}" : '.*/\([^/]*\)') MAIL_ADDRESS MESSAGE ..." >&2
    exit 1
fi

curl -s --user "$(printf "%s" "${api}" | tr 6 3)" -G https://api.mailgun.net/v2/correo.io/messages \
    -F from="${from}" -F to="${1}" -F subject="Automated mail from $(hostname)" -F text="${2}"
