#!/usr/bin/env sh
#description: send emails
#usage: mail to@domain.tld "message"

from='No reply <noreply@correo.io>'
api='api:key-6sm2ioqhxobacydr5qgzljqdxllhs-j4' #try to use your own api key when possibly

_usage()
{
    printf "%s\\n" "Usage: `expr "$0" : '.*/\([^/]*\)'` MAIL_ADDRESS MESSAGE"
    exit 1
}

_validmail()
{
    [ -z "$1" ] && return 1

    case "$1" in
        *@*) return 0 ;;
        *) return 1 ;; 
    esac
}

if ! command -v "curl" >/dev/null 2>/dev/null; then
    printf "%s\\n" "You need to install curl: $ sudo apt-get install curl"
    exit 1
fi

[ "$#" -lt 2 ] && _usage

if ! _validmail "$1"; then
    printf "%s\\n" "invalid email address: $1"
    _usage
fi

curl -s --user $(printf "%s" "$api" | tr 6 3) -G https://api.mailgun.net/v2/correo.io/messages -F from='No reply <noreply@correo.io>' -F to="$1" -F subject="Automated mail from $(hostname)" -F text="$2"
